In [3]:
import numpy as np

# Определение матриц A, B и C
A = np.array([[1, 2, 1], [-2, 1, 1]])
B = np.array([[3, 1], [-1, 0], [2, 4]])
C = np.array([[-2, 2], [1, -1], [1, 2]])

# Выполнение операций над матрицами
result1 = A + 2 * B.T  # Транспонирование матрицы B для согласования размерностей
result2 = B + 2 * C

# Вывод результатов
print("Результат операции A + 2B:")
print(result1)

print("Результат операции B + 2C:")
print(result2)

Результат операции A + 2B:
[[7 0 5]
 [0 1 9]]
Результат операции B + 2C:
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [5]:
import numpy as np

# Создание матрицы 8x8, заполненной нулями
matrix = np.zeros((8, 8), dtype=int)

# Заполнение матрицы значениями в альтернативном шахматном порядке через срезы массива
matrix[1::2, ::2] = 1  # Заполнение нечетных строк и четных столбцов значениями 1
matrix[::2, 1::2] = 1  # Заполнение четных строк и нечетных столбцов значениями 1

# Вывод матрицы
print(matrix)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
# Создание первого вектора
vector1 = np.arange(0, 1.5, 0.1)

# Создание второго вектора
vector2 = np.arange(1, 7)

# Преобразование первого вектора в матрицу 5x3
matrix1 = np.reshape(vector1, (5, 3))

# Преобразование второго вектора в матрицу 3x2
matrix2 = np.reshape(vector2, (3, 2))

# Перемножение матриц
result = np.dot(matrix1, matrix2)

# Вывод матриц и результата перемножения
print("Первая матрица (5x3):")
print(matrix1)
print()

print("Вторая матрица (3x2):")
print(matrix2)
print()

print("Результат перемножения матриц:")
print(result)

Первая матрица (5x3):
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]

Вторая матрица (3x2):
[[1 2]
 [3 4]
 [5 6]]

Результат перемножения матриц:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [7]:
# Создание вектора из значений 1, 3, 5, 7 и так далее
vector = np.arange(1, 73, 2, dtype=np.int32)

# Выделение элементов вектора, кратных 3
result = vector[vector % 3 == 0]

# Вывод результата
print(result)

[ 3  9 15 21 27 33 39 45 51 57 63 69]
